export const GDOCS_TOOLS = [
  // Document CRUD
  'GOOGLEDOCS_CREATE_DOCUMENT',
  'GOOGLEDOCS_CREATE_DOCUMENT_MARKDOWN',
  'GOOGLEDOCS_COPY_DOCUMENT',
  'GOOGLEDOCS_GET_DOCUMENT_BY_ID',
  'GOOGLEDOCS_GET_DOCUMENT_PLAINTEXT',
  'GOOGLEDOCS_SEARCH_DOCUMENTS',
  'GOOGLEDOCS_EXPORT_DOCUMENT_AS_PDF',

  // Content insertion
  'GOOGLEDOCS_INSERT_TEXT_ACTION',
  'GOOGLEDOCS_INSERT_INLINE_IMAGE',
  'GOOGLEDOCS_INSERT_PAGE_BREAK',
  'GOOGLEDOCS_INSERT_TABLE_ACTION',
  'GOOGLEDOCS_INSERT_TABLE_COLUMN',

  // Content modification
  'GOOGLEDOCS_UPDATE_EXISTING_DOCUMENT',
  'GOOGLEDOCS_UPDATE_DOCUMENT_MARKDOWN',
  'GOOGLEDOCS_UPDATE_DOCUMENT_SECTION_MARKDOWN',
  'GOOGLEDOCS_UPDATE_DOCUMENT_STYLE',
  'GOOGLEDOCS_UPDATE_TABLE_ROW_STYLE',
  'GOOGLEDOCS_REPLACE_ALL_TEXT',
  'GOOGLEDOCS_REPLACE_IMAGE',

  // Content deletion
  'GOOGLEDOCS_DELETE_CONTENT_RANGE',
  'GOOGLEDOCS_DELETE_TABLE_COLUMN',
  'GOOGLEDOCS_DELETE_TABLE_ROW',

  // Headers, footers, footnotes
  'GOOGLEDOCS_CREATE_HEADER',
  'GOOGLEDOCS_CREATE_FOOTER',
  'GOOGLEDOCS_CREATE_FOOTNOTE',
  'GOOGLEDOCS_DELETE_HEADER',
  'GOOGLEDOCS_DELETE_FOOTER',

  // Bullets
  'GOOGLEDOCS_CREATE_PARAGRAPH_BULLETS',
  'GOOGLEDOCS_DELETE_PARAGRAPH_BULLETS',

  // Named ranges
  'GOOGLEDOCS_CREATE_NAMED_RANGE',
  'GOOGLEDOCS_DELETE_NAMED_RANGE',

  // Tables
  'GOOGLEDOCS_UNMERGE_TABLE_CELLS',
  'GOOGLEDOCS_LIST_SPREADSHEET_CHARTS',
];
