// Curated subset of GitHub's 867 tools — the most useful for daily workflows
export const GITHUB_TOOLS = [
  // Issues
  'GITHUB_CREATE_AN_ISSUE',
  'GITHUB_GET_AN_ISSUE',
  'GITHUB_UPDATE_AN_ISSUE',
  'GITHUB_LIST_REPOSITORY_ISSUES',
  'GITHUB_SEARCH_ISSUES_AND_PULL_REQUESTS',
  'GITHUB_CREATE_AN_ISSUE_COMMENT',
  'GITHUB_LIST_ISSUE_COMMENTS',
  'GITHUB_ADD_LABELS_TO_AN_ISSUE',
  'GITHUB_REMOVE_A_LABEL_FROM_AN_ISSUE',
  'GITHUB_ADD_ASSIGNEES_TO_AN_ISSUE',
  'GITHUB_LOCK_AN_ISSUE',
  'GITHUB_UNLOCK_AN_ISSUE',

  // Pull requests
  'GITHUB_CREATE_A_PULL_REQUEST',
  'GITHUB_GET_A_PULL_REQUEST',
  'GITHUB_UPDATE_A_PULL_REQUEST',
  'GITHUB_LIST_PULL_REQUESTS',
  'GITHUB_FIND_PULL_REQUESTS',
  'GITHUB_MERGE_A_PULL_REQUEST',
  'GITHUB_LIST_PULL_REQUESTS_FILES',
  'GITHUB_LIST_COMMITS_ON_A_PULL_REQUEST',
  'GITHUB_CREATE_A_REVIEW_FOR_A_PULL_REQUEST',
  'GITHUB_LIST_REVIEWS_FOR_A_PULL_REQUEST',
  'GITHUB_LIST_REVIEW_COMMENTS_ON_A_PULL_REQUEST',
  'GITHUB_REQUEST_REVIEWERS_FOR_A_PULL_REQUEST',
  'GITHUB_UPDATE_A_PULL_REQUEST_BRANCH',
  'GITHUB_CHECK_IF_PULL_REQUEST_HAS_BEEN_MERGED',

  // Repositories
  'GITHUB_GET_A_REPOSITORY',
  'GITHUB_LIST_REPOSITORIES_FOR_THE_AUTHENTICATED_USER',
  'GITHUB_LIST_ORGANIZATION_REPOSITORIES',
  'GITHUB_FIND_REPOSITORIES',
  'GITHUB_SEARCH_REPOSITORIES',
  'GITHUB_CREATE_A_REPOSITORY_FOR_THE_AUTHENTICATED_USER',
  'GITHUB_CREATE_AN_ORGANIZATION_REPOSITORY',
  'GITHUB_LIST_REPOSITORY_TOPICS',
  'GITHUB_LIST_REPOSITORY_LANGUAGES',
  'GITHUB_LIST_REPOSITORY_CONTRIBUTORS',
  'GITHUB_GET_A_REPOSITORY_README',

  // Branches & refs
  'GITHUB_LIST_BRANCHES',
  'GITHUB_GET_A_BRANCH',
  'GITHUB_CREATE_A_REFERENCE',
  'GITHUB_DELETE_A_REFERENCE',
  'GITHUB_MERGE_A_BRANCH',
  'GITHUB_RENAME_A_BRANCH',

  // Commits
  'GITHUB_LIST_COMMITS',
  'GITHUB_GET_A_COMMIT',
  'GITHUB_COMPARE_TWO_COMMITS',
  'GITHUB_SEARCH_COMMITS',
  'GITHUB_CREATE_A_COMMIT_COMMENT',

  // Files & content
  'GITHUB_GET_REPOSITORY_CONTENT',
  'GITHUB_CREATE_OR_UPDATE_FILE_CONTENTS',
  'GITHUB_DELETE_A_FILE',
  'GITHUB_GET_A_TREE',
  'GITHUB_GET_RAW_REPOSITORY_CONTENT',
  'GITHUB_COMMIT_MULTIPLE_FILES',

  // Releases
  'GITHUB_CREATE_A_RELEASE',
  'GITHUB_GET_THE_LATEST_RELEASE',
  'GITHUB_LIST_RELEASES',
  'GITHUB_GET_A_RELEASE_BY_TAG_NAME',
  'GITHUB_UPDATE_A_RELEASE',
  'GITHUB_GENERATE_RELEASE_NOTES',

  // Actions & workflows
  'GITHUB_LIST_REPOSITORY_WORKFLOWS',
  'GITHUB_LIST_WORKFLOW_RUNS_FOR_A_REPOSITORY',
  'GITHUB_GET_A_WORKFLOW_RUN',
  'GITHUB_LIST_JOBS_FOR_A_WORKFLOW_RUN',
  'GITHUB_CREATE_A_WORKFLOW_DISPATCH_EVENT',
  'GITHUB_CANCEL_WORKFLOW_RUN',
  'GITHUB_RE_RUN_A_WORKFLOW',
  'GITHUB_RE_RUN_FAILED_JOBS_FROM_A_WORKFLOW_RUN',
  'GITHUB_DOWNLOAD_WORKFLOW_RUN_LOGS',

  // Labels & milestones
  'GITHUB_LIST_LABELS_FOR_A_REPOSITORY',
  'GITHUB_CREATE_A_LABEL',
  'GITHUB_LIST_MILESTONES',

  // Users & orgs
  'GITHUB_GET_THE_AUTHENTICATED_USER',
  'GITHUB_GET_A_USER',
  'GITHUB_GET_AN_ORGANIZATION',
  'GITHUB_LIST_ORGANIZATION_MEMBERS',

  // Notifications
  'GITHUB_LIST_NOTIFICATIONS',
  'GITHUB_MARK_NOTIFICATIONS_AS_READ',

  // Stars & watching
  'GITHUB_STAR_A_REPOSITORY_FOR_THE_AUTHENTICATED_USER',
  'GITHUB_LIST_REPOSITORIES_STARRED_BY_THE_AUTHENTICATED_USER',

  // Code search
  'GITHUB_SEARCH_CODE',

  // Gists
  'GITHUB_CREATE_A_GIST',
  'GITHUB_LIST_GISTS_FOR_THE_AUTHENTICATED_USER',

  // Collaborators & teams
  'GITHUB_LIST_REPOSITORY_COLLABORATORS',
  'GITHUB_ADD_A_REPOSITORY_COLLABORATOR',
  'GITHUB_LIST_TEAMS',

  // Security
  'GITHUB_LIST_CODE_SCANNING_ALERTS_FOR_A_REPOSITORY',
  'GITHUB_LIST_SECRET_SCANNING_ALERTS_FOR_A_REPOSITORY',

  // Forks
  'GITHUB_CREATE_A_FORK',
  'GITHUB_LIST_FORKS',
];
