export const GMAIL_TOOLS = [
  'GMAIL_FETCH_EMAILS',
  'GMAIL_SEND_EMAIL',
  'GMAIL_CREATE_EMAIL_DRAFT',
  'GMAIL_REPLY_TO_THREAD',
  'GMAIL_GET_PROFILE',
  'GMAIL_FETCH_MESSAGE_BY_MESSAGE_ID',
  'GMAIL_LIST_LABELS',
  'GMAIL_ADD_LABEL_TO_EMAIL',
];
