export const LINEAR_TOOLS = [
  'LINEAR_CREATE_LINEAR_ISSUE',
  'LINEAR_LIST_LINEAR_ISSUES',
  'LINEAR_GET_LINEAR_ISSUE',
  'LINEAR_UPDATE_LINEAR_ISSUE',
  'LINEAR_LIST_LINEAR_PROJECTS',
  'LINEAR_LIST_LINEAR_TEAMS',
];
