export const ACTION_REGISTRY_VERSION = '1' as const;

export type ActionPolicy = 'read' | 'approval';
export interface ActionDeliveryContract {
  policy: ActionPolicy;
  provider: 'composio';
  idempotency: 'provider_key' | 'none';
  retry: 'safe_query' | 'never_after_dispatch';
  reconciliation: 'provider_lookup' | 'manual_required';
}
export type ActionDecision =
  | { kind: ActionPolicy }
  | {
      kind: 'deny';
      reason:
        | 'unknown_action'
        | 'registry_version_mismatch'
        | 'metadata_validation_failed';
    };

const READ_ACTIONS = [
  'GMAIL_FETCH_EMAILS',
  'GMAIL_GET_PROFILE',
  'GMAIL_FETCH_MESSAGE_BY_MESSAGE_ID',
  'GMAIL_LIST_LABELS',
  'GOOGLECALENDAR_FIND_EVENT',
  'GOOGLECALENDAR_EVENTS_LIST',
  'GOOGLECALENDAR_LIST_CALENDARS',
  'GOOGLECALENDAR_GET_CALENDAR',
  'GOOGLECALENDAR_FIND_FREE_SLOTS',
  'GOOGLECALENDAR_GET_CURRENT_DATE_TIME',
  'GOOGLECALENDAR_EVENTS_LIST_ALL_CALENDARS',
  'GOOGLECALENDAR_FREE_BUSY_QUERY',
  'GOOGLECALENDAR_EVENTS_GET',
  'GOOGLECALENDAR_EVENTS_INSTANCES',
  'GOOGLECALENDAR_COLORS_GET',
  'GOOGLECALENDAR_ACL_LIST',
  'GOOGLECALENDAR_ACL_GET',
  'GOOGLECALENDAR_CALENDAR_LIST_GET',
  'GOOGLECALENDAR_SETTINGS_GET',
  'GOOGLECALENDAR_SETTINGS_LIST',
  'GOOGLEDOCS_GET_DOCUMENT_BY_ID',
  'GOOGLEDOCS_GET_DOCUMENT_PLAINTEXT',
  'GOOGLEDOCS_SEARCH_DOCUMENTS',
  'GOOGLEDOCS_EXPORT_DOCUMENT_AS_PDF',
  'GOOGLEDOCS_LIST_SPREADSHEET_CHARTS',
  'GITHUB_GET_AN_ISSUE',
  'GITHUB_LIST_REPOSITORY_ISSUES',
  'GITHUB_SEARCH_ISSUES_AND_PULL_REQUESTS',
  'GITHUB_LIST_ISSUE_COMMENTS',
  'GITHUB_GET_A_PULL_REQUEST',
  'GITHUB_LIST_PULL_REQUESTS',
  'GITHUB_FIND_PULL_REQUESTS',
  'GITHUB_LIST_PULL_REQUESTS_FILES',
  'GITHUB_LIST_COMMITS_ON_A_PULL_REQUEST',
  'GITHUB_LIST_REVIEWS_FOR_A_PULL_REQUEST',
  'GITHUB_LIST_REVIEW_COMMENTS_ON_A_PULL_REQUEST',
  'GITHUB_CHECK_IF_PULL_REQUEST_HAS_BEEN_MERGED',
  'GITHUB_GET_A_REPOSITORY',
  'GITHUB_LIST_REPOSITORIES_FOR_THE_AUTHENTICATED_USER',
  'GITHUB_LIST_ORGANIZATION_REPOSITORIES',
  'GITHUB_FIND_REPOSITORIES',
  'GITHUB_SEARCH_REPOSITORIES',
  'GITHUB_LIST_REPOSITORY_TOPICS',
  'GITHUB_LIST_REPOSITORY_LANGUAGES',
  'GITHUB_LIST_REPOSITORY_CONTRIBUTORS',
  'GITHUB_GET_A_REPOSITORY_README',
  'GITHUB_LIST_BRANCHES',
  'GITHUB_GET_A_BRANCH',
  'GITHUB_LIST_COMMITS',
  'GITHUB_GET_A_COMMIT',
  'GITHUB_COMPARE_TWO_COMMITS',
  'GITHUB_SEARCH_COMMITS',
  'GITHUB_GET_REPOSITORY_CONTENT',
  'GITHUB_GET_A_TREE',
  'GITHUB_GET_RAW_REPOSITORY_CONTENT',
  'GITHUB_GET_THE_LATEST_RELEASE',
  'GITHUB_LIST_RELEASES',
  'GITHUB_GET_A_RELEASE_BY_TAG_NAME',
  'GITHUB_GENERATE_RELEASE_NOTES',
  'GITHUB_LIST_REPOSITORY_WORKFLOWS',
  'GITHUB_LIST_WORKFLOW_RUNS_FOR_A_REPOSITORY',
  'GITHUB_GET_A_WORKFLOW_RUN',
  'GITHUB_LIST_JOBS_FOR_A_WORKFLOW_RUN',
  'GITHUB_DOWNLOAD_WORKFLOW_RUN_LOGS',
  'GITHUB_LIST_LABELS_FOR_A_REPOSITORY',
  'GITHUB_LIST_MILESTONES',
  'GITHUB_GET_THE_AUTHENTICATED_USER',
  'GITHUB_GET_A_USER',
  'GITHUB_GET_AN_ORGANIZATION',
  'GITHUB_LIST_ORGANIZATION_MEMBERS',
  'GITHUB_LIST_NOTIFICATIONS',
  'GITHUB_LIST_REPOSITORIES_STARRED_BY_THE_AUTHENTICATED_USER',
  'GITHUB_SEARCH_CODE',
  'GITHUB_LIST_GISTS_FOR_THE_AUTHENTICATED_USER',
  'GITHUB_LIST_REPOSITORY_COLLABORATORS',
  'GITHUB_LIST_TEAMS',
  'GITHUB_LIST_CODE_SCANNING_ALERTS_FOR_A_REPOSITORY',
  'GITHUB_LIST_SECRET_SCANNING_ALERTS_FOR_A_REPOSITORY',
  'GITHUB_LIST_FORKS',
] as const;

const APPROVAL_ACTIONS = [
  'GMAIL_SEND_EMAIL',
  'GMAIL_CREATE_EMAIL_DRAFT',
  'GMAIL_REPLY_TO_THREAD',
  'GMAIL_ADD_LABEL_TO_EMAIL',
  'GOOGLECALENDAR_CREATE_EVENT',
  'GOOGLECALENDAR_DELETE_EVENT',
  'GOOGLECALENDAR_PATCH_EVENT',
  'GOOGLECALENDAR_UPDATE_EVENT',
  'GOOGLECALENDAR_QUICK_ADD',
  'GOOGLECALENDAR_REMOVE_ATTENDEE',
  'GOOGLECALENDAR_BATCH_EVENTS',
  'GOOGLECALENDAR_CLEAR_CALENDAR',
  'GOOGLECALENDAR_DUPLICATE_CALENDAR',
  'GOOGLECALENDAR_PATCH_CALENDAR',
  'GOOGLECALENDAR_EVENTS_MOVE',
  'GOOGLECALENDAR_ACL_INSERT',
  'GOOGLECALENDAR_ACL_DELETE',
  'GOOGLECALENDAR_ACL_PATCH',
  'GOOGLECALENDAR_ACL_UPDATE',
  'GOOGLECALENDAR_CALENDARS_UPDATE',
  'GOOGLECALENDAR_CALENDARS_DELETE',
  'GOOGLECALENDAR_CALENDAR_LIST_INSERT',
  'GOOGLECALENDAR_CALENDAR_LIST_DELETE',
  'GOOGLECALENDAR_CALENDAR_LIST_PATCH',
  'GOOGLECALENDAR_CALENDAR_LIST_UPDATE',
  'GOOGLECALENDAR_EVENTS_IMPORT',
  'GOOGLEDOCS_CREATE_DOCUMENT',
  'GOOGLEDOCS_CREATE_DOCUMENT_MARKDOWN',
  'GOOGLEDOCS_COPY_DOCUMENT',
  'GOOGLEDOCS_INSERT_TEXT_ACTION',
  'GOOGLEDOCS_INSERT_INLINE_IMAGE',
  'GOOGLEDOCS_INSERT_PAGE_BREAK',
  'GOOGLEDOCS_INSERT_TABLE_ACTION',
  'GOOGLEDOCS_INSERT_TABLE_COLUMN',
  'GOOGLEDOCS_UPDATE_EXISTING_DOCUMENT',
  'GOOGLEDOCS_UPDATE_DOCUMENT_MARKDOWN',
  'GOOGLEDOCS_UPDATE_DOCUMENT_SECTION_MARKDOWN',
  'GOOGLEDOCS_UPDATE_DOCUMENT_STYLE',
  'GOOGLEDOCS_UPDATE_TABLE_ROW_STYLE',
  'GOOGLEDOCS_REPLACE_ALL_TEXT',
  'GOOGLEDOCS_REPLACE_IMAGE',
  'GOOGLEDOCS_DELETE_CONTENT_RANGE',
  'GOOGLEDOCS_DELETE_TABLE_COLUMN',
  'GOOGLEDOCS_DELETE_TABLE_ROW',
  'GOOGLEDOCS_CREATE_HEADER',
  'GOOGLEDOCS_CREATE_FOOTER',
  'GOOGLEDOCS_CREATE_FOOTNOTE',
  'GOOGLEDOCS_DELETE_HEADER',
  'GOOGLEDOCS_DELETE_FOOTER',
  'GOOGLEDOCS_CREATE_PARAGRAPH_BULLETS',
  'GOOGLEDOCS_DELETE_PARAGRAPH_BULLETS',
  'GOOGLEDOCS_CREATE_NAMED_RANGE',
  'GOOGLEDOCS_DELETE_NAMED_RANGE',
  'GOOGLEDOCS_UNMERGE_TABLE_CELLS',
  'GITHUB_CREATE_AN_ISSUE',
  'GITHUB_UPDATE_AN_ISSUE',
  'GITHUB_CREATE_AN_ISSUE_COMMENT',
  'GITHUB_ADD_LABELS_TO_AN_ISSUE',
  'GITHUB_REMOVE_A_LABEL_FROM_AN_ISSUE',
  'GITHUB_ADD_ASSIGNEES_TO_AN_ISSUE',
  'GITHUB_LOCK_AN_ISSUE',
  'GITHUB_UNLOCK_AN_ISSUE',
  'GITHUB_CREATE_A_PULL_REQUEST',
  'GITHUB_UPDATE_A_PULL_REQUEST',
  'GITHUB_MERGE_A_PULL_REQUEST',
  'GITHUB_CREATE_A_REVIEW_FOR_A_PULL_REQUEST',
  'GITHUB_REQUEST_REVIEWERS_FOR_A_PULL_REQUEST',
  'GITHUB_UPDATE_A_PULL_REQUEST_BRANCH',
  'GITHUB_CREATE_A_REPOSITORY_FOR_THE_AUTHENTICATED_USER',
  'GITHUB_CREATE_AN_ORGANIZATION_REPOSITORY',
  'GITHUB_CREATE_A_REFERENCE',
  'GITHUB_DELETE_A_REFERENCE',
  'GITHUB_MERGE_A_BRANCH',
  'GITHUB_RENAME_A_BRANCH',
  'GITHUB_CREATE_A_COMMIT_COMMENT',
  'GITHUB_CREATE_OR_UPDATE_FILE_CONTENTS',
  'GITHUB_DELETE_A_FILE',
  'GITHUB_COMMIT_MULTIPLE_FILES',
  'GITHUB_CREATE_A_RELEASE',
  'GITHUB_UPDATE_A_RELEASE',
  'GITHUB_CREATE_A_WORKFLOW_DISPATCH_EVENT',
  'GITHUB_CANCEL_WORKFLOW_RUN',
  'GITHUB_RE_RUN_A_WORKFLOW',
  'GITHUB_RE_RUN_FAILED_JOBS_FROM_A_WORKFLOW_RUN',
  'GITHUB_CREATE_A_LABEL',
  'GITHUB_MARK_NOTIFICATIONS_AS_READ',
  'GITHUB_STAR_A_REPOSITORY_FOR_THE_AUTHENTICATED_USER',
  'GITHUB_CREATE_A_GIST',
  'GITHUB_ADD_A_REPOSITORY_COLLABORATOR',
  'GITHUB_CREATE_A_FORK',
] as const;

export const ACTION_REGISTRY: ReadonlyMap<string, ActionPolicy> = new Map([
  ...READ_ACTIONS.map((name) => [name, 'read'] as const),
  ...APPROVAL_ACTIONS.map((name) => [name, 'approval'] as const),
]);

export const ACTION_DELIVERY_REGISTRY: ReadonlyMap<string, ActionDeliveryContract> = new Map(
  [...ACTION_REGISTRY].map(([name, policy]) => [
    name,
    policy === 'read'
      ? {
          policy,
          provider: 'composio',
          idempotency: 'none',
          retry: 'safe_query',
          reconciliation: 'provider_lookup',
        }
      : {
          policy,
          provider: 'composio',
          // The pinned Composio link/tool surface does not expose a documented
          // end-to-end mutation idempotency guarantee. The local key is an
          // audit correlation key only; ambiguous delivery is never retried.
          idempotency: 'none',
          retry: 'never_after_dispatch',
          reconciliation: 'manual_required',
        },
  ]),
);

export function getActionDeliveryContract(name: string): ActionDeliveryContract | undefined {
  return ACTION_DELIVERY_REGISTRY.get(name);
}

export function classifyAction(
  toolName: string,
  context: { registryVersion: string; metadataValidated: boolean },
): ActionDecision {
  if (context.registryVersion !== ACTION_REGISTRY_VERSION) {
    return { kind: 'deny', reason: 'registry_version_mismatch' };
  }
  if (!context.metadataValidated) {
    return { kind: 'deny', reason: 'metadata_validation_failed' };
  }
  const policy = ACTION_REGISTRY.get(toolName);
  return policy
    ? { kind: policy }
    : { kind: 'deny', reason: 'unknown_action' };
}
